"""add_sectional_embeddings

Revision ID: ad5da92d3a14
Revises: 7adbfdf43b0d
Create Date: 2025-10-11 08:36:30.023900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ad5da92d3a14'
down_revision: Union[str, None] = '7adbfdf43b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting', sa.Column('required_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('job_posting', sa.Column('preferred_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('job_posting', sa.Column('description_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('resume', sa.Column('skills_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('resume', sa.Column('experience_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('resume', sa.Column('projects_embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'projects_embedding')
    op.drop_column('resume', 'experience_embedding')
    op.drop_column('resume', 'skills_embedding')
    op.drop_column('job_posting', 'description_embedding')
    op.drop_column('job_posting', 'preferred_embedding')
    op.drop_column('job_posting', 'required_embedding')
    # ### end Alembic commands ###

