"""add resume_sentence and job_sentence tables

Revision ID: a96117a55003
Revises: eb2d17db17c3
Create Date: 2025-10-16 15:14:43.457401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a96117a55003'
down_revision: Union[str, None] = 'eb2d17db17c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sentence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_posting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sentence_job_id'), 'job_sentence', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_sentence_section'), 'job_sentence', ['section'], unique=False)
    op.create_table('resume_sentence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_sentence_resume_id'), 'resume_sentence', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_sentence_section'), 'resume_sentence', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_sentence_section'), table_name='resume_sentence')
    op.drop_index(op.f('ix_resume_sentence_resume_id'), table_name='resume_sentence')
    op.drop_table('resume_sentence')
    op.drop_index(op.f('ix_job_sentence_section'), table_name='job_sentence')
    op.drop_index(op.f('ix_job_sentence_job_id'), table_name='job_sentence')
    op.drop_table('job_sentence')
    # ### end Alembic commands ###

